name: car_learning_app
description: A Flutter app to help users learn about cars and their specifications.
publish_to: "none"

version: 1.0.1+2    # change version in android/app/build.gradle.kts

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  csv: ^6.0.0  # Add this for CSV parsing
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  tutorial_coach_mark: ^1.3.0
  firebase_core: ^4.0.0
  firebase_storage: ^13.0.0
  firebase_analytics: ^12.0.0
  google_mobile_ads: ^5.3.1
  dio:              ^5.0.0 
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.3"
  flutter_native_splash: ^2.4.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true

flutter:
  uses-material-design: true

  # Declare assets used in the app
  assets:
    - assets/cars.csv
    - assets/home/
    - assets/icons/
    - assets/images/
